import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule, MatCheckboxModule, MatToolbarModule, MatCardModule, MatInputModule, MatTableModule, MatPaginatorModule, MatSortModule, MatDialogModule, MatChipsModule, MatSelectModule, MatIconModule, MatDividerModule, MatRadioModule, MatProgressBarModule, MatListModule, MatDatepickerModule, MatNativeDateModule, MatExpansionModule, MatStepperModule, MatTabsModule, MatTooltipModule, MatTreeModule, MatMenuModule, MatProgressSpinnerModule, MatSidenavModule, MatSlideToggleModule, MatRippleModule, MatSliderModule, MatGridListModule, MatAutocompleteModule } from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatCardModule,
    MatInputModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatDialogModule,
    MatChipsModule,
    MatSelectModule,
    MatIconModule,
    MatDividerModule,
    MatRadioModule,
    MatProgressBarModule,
    MatListModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatStepperModule,
    MatTabsModule,
    MatTooltipModule,
    MatTreeModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatRippleModule,
    MatSliderModule,
    MatGridListModule,
    MatAutocompleteModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatCardModule,
    MatInputModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatDialogModule,
    MatChipsModule,
    MatSelectModule,
    MatIconModule,
    MatDividerModule,
    MatRadioModule,
    MatProgressBarModule,
    MatListModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatStepperModule,
    MatTabsModule,
    MatTooltipModule,
    MatTreeModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatSlideToggleModule,
    MatRippleModule,
    MatSliderModule,
    MatGridListModule,
    MatAutocompleteModule
  ],
  declarations: []
})
export class AppMaterialModule { }
